default:
  image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - dotnet build -c Release
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "bin/release/*.nupkg" --source gitlab
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
  environment: production
